name: Report

on:
  push:
    branches: ['*']
  # manual run
  workflow_dispatch:
  # scheduled run (daily at 2:15)
  schedule:
    - cron: "15 2 * * *"

jobs:
  report:
    name: "Report"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: "Run report"
        run: |
          bash ./scripts/report.sh

      - name: "Show report"
        run: |
          echo "VPP API List"
          echo "============"
          echo
          cat vppapi_list.txt

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: vppapi_list
          path: vppapi_list.txt
